### ISSUE TITLE
Sphinx support

### ISSUE THREAD

**Issue by fomcl** [gitbucket/gitbucket-pages-plugin#18]
Hi,

Great plugin! We are using Sphinx (http://www.sphinx-doc.org/en/stable/) to document our Python projects. This allows you to generate html documentation based on documentation in (generated) restructuredText (.rst) files. Each Python module has its own .html file, and in the directory tree are several subdirectories, e.g. _static, _modules, etc. that may each also contain html and other files. For example, in _modules, there is an index.html and a folder with colour coded versions of the Python source code itself. From within the documentation of e.g. a function or class, it is possible to click a 'source'  link and one immediately sees how that function or class was actually implemented. Great, but I am not yet able to get this working with your plugin. If I push a file ./mypackage/mymodule/myscript.html to the Gitbucket wiki, can I still link to that file? My overall goal is that I automatically update the wiki documentation with each commit (with a hook) by running sphinx and pushing the files to the wiki repo.

Thanks!

Albert-Jan

**Comment by fomcl** [comment]
Hi again, I should add that Sphinx is not the only autodoc package, there's Doxygen, Roxygen and probably more.

**Comment by yaroot** [comment]
Hi, you could push the html files to an orphan branch called _gb-pages_ (default) or _docs_ folder under _master_ branch (change in repo settings), and visit _<repo_url>/pages_, this plugin will serve the file as is. The built-in wiki only supports markdown iirc.

**Comment by aadrian** [comment]
> The built-in wiki only supports markdown iirc.

With this plug-in https://github.com/asciidoctor/gitbucket-asciidoctor-plugin **AsciiDoc** as a format should work too and with this one https://github.com/amuramatsu/gitbucket-rst-plugin  **ReSTructured text** too.

**Comment by yaroot** [comment]
Ah, didn't know that.

Closing as this is not an issue, feel free to reply here or at gitter channel.

**Comment by fomcl** [comment]
Hi Yaroot and Aadrian,

Thanks for your replies. I'll try both approaches. Great to know that one way or another it'll work. Very curious how the .rst will render.

Best wishes,
Albert-Jan
