### ISSUE TITLE
plugin cannot load css file

### ISSUE THREAD

**Issue by yeqinfu** [gitbucket/gitbucket-pages-plugin#27]
![image](https://user-images.githubusercontent.com/13571699/77163840-ed564680-6ae9-11ea-8ef2-1b41e273db57.png)
I put my static website on branch gb-pages.
And I access http://ip:port/test/pages
![image](https://user-images.githubusercontent.com/13571699/77164039-605fbd00-6aea-11ea-87a1-b8a0570979bc.png)
Am I put wrong path?

**Comment by Tak-Takano** [comment]
I also encountered the same issue and resolved by attaching the last '/'.
Try to access http://ip:port/test/pages/
