### ISSUE TITLE
Images and CSS from the repository using pages are not found.

### ISSUE THREAD

**Issue by mibi88** [gitbucket/gitbucket-pages-plugin#35]
On the website, images and CSS files are not found by chromium, but are in the repository.

**Comment by yaroot** [comment]
How does the url look like? Do you use any site generator (jekyll or anything)?

**Comment by mibi88** [comment]
It's a relative path. I am not using a site generator.

Thank you.
Mibi88

**Comment by yaroot** [comment]
Okay I think this is fixed
